[analysis]
min_supports = [6, 4]
jump_distances = [0.0]
grami_alphas = [1.0]
grami_max_fsm_size = 9
gis_configs = [
    ["gpitch", "offset"],
    ["pitch", "offset"],
    ["pc", "offset"]
]
connect_same_time_options = [false]
window_size = 4.0
