[analysis]
miners = ["gspan"]
min_supports = [10, 8, 6]
jump_distances = [0.0, 0.5]
grami_max_fsm_size = 9
gis_configs = [
    ["gpitch", "offset"],
    ["pitch", "offset"],
    ["pc", "offset"],
    ["gpc", "offset"]
]
connect_same_time_options = [true, false]
